In [1]:
import numpy as np
from scipy.io import loadmat
from sklearn.preprocessing import MinMaxScaler
from functions import fun_init

In [2]:
# --- 1. 加载数据（训练集特征+标签）---
A = loadmat('A_matlab.mat')['A_matlab']

In [3]:
total_num = 88
temp = np.arange(88)

In [4]:
# --- 2. 训练 / 测试集索引 ---
M, N = 71, 17
train_idx = temp[:M]
test_idx = temp[M:M+N]

In [5]:
# --- 3. 特征选择索引（0-22）对应 MATLAB 的 1:23 ---
feat_idx = list(range(23))

In [6]:
# --- 4. 调用初始化函数 ---
ps_output, ps_input, p_train, p_test, t_train, t_test, T_train, T_test, P_train, P_test = fun_init(
    A, train_idx, feat_idx, test_idx
)
ps_output, ps_input, p_train, p_test, t_train, t_test, T_train, T_test, P_train, P_test

(MinMaxScaler(),
 MinMaxScaler(),
 array([[0.49358496, 0.44204928, 0.28723119, ..., 0.73227963, 0.64286181,
         0.47794779],
        [0.09386443, 0.08896427, 0.04106979, ..., 0.93841668, 1.        ,
         0.14671467],
        [0.55199023, 0.49143595, 0.33749156, ..., 0.52316519, 0.62456897,
         0.55175518],
        ...,
        [0.7567999 , 0.68233088, 0.56267023, ..., 0.50110466, 0.54688754,
         0.61746175],
        [0.57298116, 0.50681193, 0.35682224, ..., 0.75081771, 0.60623283,
         0.47164716],
        [0.7080809 , 0.54770399, 0.50071838, ..., 0.51733397, 0.4175867 ,
         0.43294329]]),
 array([[ 8.11381107e-01,  6.94279077e-01,  6.40100695e-01,
          6.66765660e-01,  7.31376257e-01,  7.15605722e-01,
          7.57082978e-01,  7.57380568e-01,  7.00638763e-01,
          6.59715636e-01,  4.75338717e-01,  6.21831466e-01,
          3.72377022e-01,  4.73430219e-01,  3.72511516e-01,
          4.77722567e-01,  3.15126856e-01,  6.23410653e-01,
          5.333

In [7]:
from functions import selectByGWOfun

In [8]:
# 参数设置
SearchAgents_no = 4
T = 10
dim = 13
feature_num = 23
lb = 0
ub = 1

# 运行灰狼特征选择
Alpha_position, iterations, accuracy, param_a, All_position, All_score = selectByGWOfun(
    P_train, T_train, P_test, T_test,
    SearchAgents_no, T, dim, feature_num, lb, ub
)
Alpha_position

array([1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0])

In [9]:
# 特征排序并选择前dim个
vsort = np.sort(Alpha_position)[::-1]
S = np.argsort(Alpha_position)[::-1]
select_indices = S[:dim]
label_name = ["NDVI", "EVI2", "RVI", "DVI", "RDVI", "MSR", "MCARI", "OSAVI", "WDRVI", "NIR", "对比度", "相关性", "熵",
          "平稳度", "能量", "同质性", "Rmean", "Gmean", "Bmean", "Rstd", "Gstd", "Bstd", "Mask_rate"]

indexselect_name = [label_name[i] for i in select_indices]

print("选择的特征编号：", select_indices)
print("选择的特征名：", indexselect_name)

选择的特征编号： [ 0  2 18  4  5 14 13  7  8  9  1  3  6]
选择的特征名： ['NDVI', 'RVI', 'Bmean', 'RDVI', 'MSR', '能量', '平稳度', 'OSAVI', 'WDRVI', 'NIR', 'EVI2', 'DVI', 'MCARI']
